### ISSUE TITLE
As an admin i can post an idea to the pitch library and link it to the ideator

### ISSUE THREAD

**Issue by HussienKamal** [GUC-SE-2015/i2b#18]

**Comment by HussienKamal** [comment]
enta dlw2ty me7tag te3mel form lel insertion fel database we teinsert @A7medNaguib

**Comment by HussienKamal** [comment]
@A7medNaguib ana shayef en enta msh me7tag t7ot authentication lel admin we hwa da5el yepost fel pitch library 3ashan hwa aslan authenticated fel awal we gheer kda dh admin :D

**Comment by A7medNaguib** [comment]
@HussienKamal el fekra en "add pitch" msh exclusive lel admins bas w mafeesh condition y-check el user da admin wala la2 ... fa ana 7atet el authentication da e7tyaty msh aktar :smile:
