### ISSUE TITLE
As an Idea Consultant I can view the full description of any idea.

### ISSUE THREAD

**Issue by JirayrB** [GUC-SE-2015/i2b#22]

**Comment by JirayrB** [comment]
@omarhisham please review :)

**Comment by HussienKamal** [comment]
ana shoft el code bas 3andy so2al .. enta 3amel ely yeshoof el full description el idea consultant bas ? walla ay 7ad ? @JirayrB

**Comment by HussienKamal** [comment]
ana shoft el code we 3amaltelo testing bas hya el fekra enak tfara2 mabeen el idea consultant we ideator we volunteers we kda m7adesh mafrood yeshoof full description gheer admins we ideator we idea consultants @JirayrB

**Comment by omarhisham** [comment]
@JirayrB working fine
